### ISSUE TITLE
Can't find the trained model and vocabulary of chapter 2, Image captioning

### ISSUE THREAD

**Issue by Moogun** [PacktPublishing/Computer-Vision-Projects-with-OpenCV-and-Python-3#1]
Hi 
I wonder if you coul point where the trained model is ? 

Thanks

**Comment by jasonsalas** [comment]
I'm having the same problem myself. You can Google to find other './model/word_count.txt' files, but the actual model isn't included with the code, and so the first pre-trained part of the example won't run.

**Comment by gblosser** [comment]
I went to the publisher website and the missing folder and files are included in the code download: https://www.packtpub.com/big-data-and-business-intelligence/computer-vision-projects-opencv-and-python-3?utm_source=github&utm_medium=repository&utm_campaign=9781789954555

**Comment by MurtazaTinwala** [comment]
If, in case, you are not able to find any file, please visit: https://www.packtpub.com/big-data-and-business-intelligence/computer-vision-projects-opencv-and-python-3?utm_source=github&utm_medium=repository&utm_campaign=9781789954555
