### ISSUE TITLE
error in import default_config    file is not present

### ISSUE THREAD

**Issue by souravgajbhiye** [PacktPublishing/Computer-Vision-Projects-with-OpenCV-and-Python-3#4]

**Comment by sarvesh-packt** [comment]
Hi @souravgajbhiye ,

We cannot see any description. Kindly provide with proper description so that it will be easy for us to get the issue.

Regards,

**Comment by hoscanoav** [comment]
![image](https://user-images.githubusercontent.com/19982184/127959901-249a2c53-543e-498f-92d7-5dce6c59e603.png)
